# Generated by Django 5.2.1 on 2025-05-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Image',
        ),
    ]
