# Generated by Django 5.2.1 on 2025-05-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_gallery_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceFeature',
            new_name='Feature',
        ),
    ]
