# Generated by Django 5.2.1 on 2025-05-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_servicefeature_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
