# Generated by Django 5.2.1 on 2025-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("phone", models.CharField()),
                ("email", models.CharField()),
                ("businessHours", models.CharField()),
                ("logo", models.URLField()),
            ],
        ),
    ]
