# Generated by Django 5.2.1 on 2025-06-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('phone', models.CharField()),
                ('email', models.CharField()),
                ('businessHours', models.CharField()),
                ('logo_path', models.ImageField(upload_to='page_images/company/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(verbose_name='Nombres Completos')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('phone', models.CharField(max_length=20, verbose_name='telefono')),
                ('company', models.CharField(verbose_name='empresa')),
                ('message', models.CharField(verbose_name='message')),
                ('subject', models.TextField(verbose_name='asunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
        ),
    ]
