# Generated by Django 5.2.1 on 2025-06-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.CharField(),
            preserve_default=False,
        ),
    ]
