# Generated by Django 5.2.1 on 2025-05-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_contactrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrequest',
            old_name='subjetc',
            new_name='subject',
        ),
    ]
