# Generated by Django 5.2.1 on 2025-05-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_subjetc_contactrequest_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='company',
            field=models.CharField(verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='fullname',
            field=models.CharField(verbose_name='Nombres Completos'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='subject',
            field=models.TextField(verbose_name='asunto'),
        ),
    ]
