# Generated by Django 5.2.1 on 2025-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slide", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slide",
            name="href",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="slide",
            name="text",
            field=models.CharField(null=True),
        ),
    ]
